### ISSUE TITLE
Setup - appveyor

### ISSUE THREAD

**Issue by dud3** [Drooids/blitz-playground#3]
Sample:
```
version: 0.26.{build}
os: Windows Server 2012 R2
configuration: RelWithDebInfo
before_build:
  - cd projects
  - genie_vs15.bat
  - cd ..
build:
  project: projects\tmp\vs2015\LumixEngine.sln
  verbosity: minimal

test_script:
- ps: >-
    git clone --depth=1  https://github.com/nem0/LumixEngine_data.git 2>&1 | % { $_.ToString() } 

    cd LumixEngine_data

    & "..\projects\tmp\vs2015\bin\RelWithDebInfo\unit_tests.exe" | Write-Output

    $wc = New-Object Net.WebClient
            $url = "https://ci.appveyor.com/api/testresults/nunit/$Env:APPVEYOR_JOB_ID"
            $wc.UploadFile($url, (Resolve-Path .\tests.xml))

- ps: >-
    & "..\projects\tmp\vs2015\bin\RelWithDebInfo\studio.exe" -run_script unit_tests/render_tests/compile_shaders.lua | Write-Output

- ps: >-
    & "..\projects\tmp\vs2015\bin\RelWithDebInfo\studio.exe" -pseudorandom_guid -run_script unit_tests/editor/main.lua | Write-Output

- ps: >-
    & "..\projects\tmp\vs2015\bin\RelWithDebInfo\app.exe" -window -pipeline pipelines/render_test.lua -script unit_tests/render_tests/main.lua | Write-Output
  
after_build:
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\animation.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\audio.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\editor.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\engine.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\lua_script.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\navigation.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\physics.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\renderer.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\studio.exe
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\animation.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\audio.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\editor.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\engine.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\lua_script.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\navigation.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\physics.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\renderer.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2015\bin\RelWithDebInfo\studio.pdb
 
artifacts:
- path: tests.xml
  name: tests.xml

- path: LumixEngine_data/unit_tests/render_tests/hdr_dof_res.tga
  name: test.tga

- path: lumix.zip
  name: lumix.zip
```
